import type { Meal } from "@/lib/coach/types";

export interface MealCatalogEntry {
  meal: Meal;
  name: string;
  // Short ingredient summary, shown under the meal name in the
  // suggestion card — what it actually is, not a recipe.
  description: string;
  // Typical serving weight, and that serving's total macros — a
  // composed meal, not a per-100g ingredient value (see
  // meal-suggestions.ts's toSuggestion for how this converts to the
  // per-100g shape POST /api/member/nutrition/log expects).
  quantityG: number;
  calories: number;
  proteinG: number;
  carbsG: number;
  fatG: number;
  // Real measurements (Carl, 2026-08-25: "needs cooking instructions and
  // measurements") — enough to actually shop for and cook this, not just
  // a macro readout.
  ingredients: string[];
  instructions: string[];
}

// Hand-written and reviewed, deliberately never LLM-generated — same
// principle as EXERCISE_CATALOG's safety tips (exercise-catalog.ts):
// nutrition numbers and instructions a member might actually act on
// don't get left to an LLM to improvise. Replaces a nearest-fit search
// over uk_food_composition (PHE's raw-ingredient reference data), which
// could only ever suggest single ingredients — Carl asked for real
// composed meals instead (2026-08-25: "high protein oats... chicken
// wraps"). Macros are realistic estimates for the stated portion, not
// lab-tested.
export const MEAL_CATALOG: MealCatalogEntry[] = [
  // Breakfast
  {
    meal: "breakfast",
    name: "High-protein oats",
    description: "Oats, whey protein, milk, banana",
    quantityG: 450,
    calories: 420,
    proteinG: 42,
    carbsG: 48,
    fatG: 8,
    ingredients: ["50g rolled oats", "250ml semi-skimmed milk", "1 scoop (30g) whey protein powder", "1 medium banana, sliced"],
    instructions: [
      "Add the oats and milk to a pan or microwave-safe bowl and cook for 2-3 minutes until thick.",
      "Stir in the protein powder until fully combined.",
      "Top with sliced banana and serve.",
    ],
  },
  {
    meal: "breakfast",
    name: "Greek yoghurt & berries with granola",
    description: "Greek yoghurt, mixed berries, granola",
    quantityG: 350,
    calories: 380,
    proteinG: 22,
    carbsG: 46,
    fatG: 10,
    ingredients: ["250g Greek yoghurt", "80g mixed berries", "40g granola"],
    instructions: ["Spoon the yoghurt into a bowl.", "Top with the berries and granola.", "Serve immediately."],
  },
  {
    meal: "breakfast",
    name: "Scrambled eggs on wholemeal toast",
    description: "3 eggs, 2 slices wholemeal toast, butter",
    quantityG: 300,
    calories: 400,
    proteinG: 28,
    carbsG: 32,
    fatG: 17,
    ingredients: ["3 medium eggs", "2 slices wholemeal bread", "5g butter", "Salt and pepper"],
    instructions: [
      "Whisk the eggs and season with salt and pepper.",
      "Melt the butter in a non-stick pan over low-medium heat and cook the eggs, stirring gently until just set.",
      "Toast the bread and serve the eggs on top.",
    ],
  },
  {
    meal: "breakfast",
    name: "Protein pancakes with berries",
    description: "Oat & protein pancakes, mixed berries, honey",
    quantityG: 300,
    calories: 380,
    proteinG: 30,
    carbsG: 40,
    fatG: 9,
    ingredients: ["60g oats (blended to a flour)", "1 scoop (30g) whey protein powder", "2 eggs", "100ml milk", "80g mixed berries"],
    instructions: [
      "Blend the oats, protein powder, eggs and milk into a smooth batter.",
      "Cook spoonfuls in a lightly oiled non-stick pan for 1-2 minutes per side until golden.",
      "Stack and top with the berries.",
    ],
  },
  {
    meal: "breakfast",
    name: "Smoked salmon & scrambled eggs",
    description: "Smoked salmon, 3 eggs",
    quantityG: 250,
    calories: 410,
    proteinG: 32,
    carbsG: 4,
    fatG: 29,
    ingredients: ["80g smoked salmon", "3 medium eggs", "Black pepper", "Squeeze of lemon"],
    instructions: [
      "Whisk the eggs and scramble gently in a non-stick pan over low heat.",
      "Serve topped with the smoked salmon.",
      "Season with black pepper and a squeeze of lemon.",
    ],
  },
  {
    meal: "breakfast",
    name: "Overnight oats with peanut butter",
    description: "Oats, milk, chia seeds, peanut butter",
    quantityG: 350,
    calories: 440,
    proteinG: 20,
    carbsG: 50,
    fatG: 16,
    ingredients: ["60g rolled oats", "200ml milk", "1 tbsp (15g) chia seeds", "1 tbsp (20g) peanut butter"],
    instructions: [
      "Combine the oats, milk and chia seeds in a jar or container.",
      "Stir in the peanut butter.",
      "Cover and refrigerate overnight; eat cold or warmed through.",
    ],
  },

  // Lunch
  {
    meal: "lunch",
    name: "Chicken wrap with salad",
    description: "Grilled chicken, tortilla wrap, salad, light mayo",
    quantityG: 320,
    calories: 480,
    proteinG: 38,
    carbsG: 46,
    fatG: 14,
    ingredients: ["150g grilled chicken breast, sliced", "1 large tortilla wrap", "Handful of mixed salad leaves", "1 tbsp (15g) light mayonnaise"],
    instructions: [
      "Warm the wrap slightly if you like.",
      "Layer the chicken, salad and mayonnaise down the centre.",
      "Fold in the sides and roll tightly.",
    ],
  },
  {
    meal: "lunch",
    name: "Chicken and rice bowl with veg",
    description: "Grilled chicken breast, basmati rice, mixed vegetables",
    quantityG: 450,
    calories: 560,
    proteinG: 45,
    carbsG: 60,
    fatG: 12,
    ingredients: ["180g chicken breast", "150g basmati rice (cooked weight)", "100g mixed vegetables"],
    instructions: [
      "Season and grill or pan-fry the chicken until cooked through, then slice.",
      "Cook the rice according to the pack instructions.",
      "Steam the vegetables and combine everything in a bowl.",
    ],
  },
  {
    meal: "lunch",
    name: "Tuna salad with wholemeal roll",
    description: "Tuna, mixed salad, wholemeal roll",
    quantityG: 350,
    calories: 430,
    proteinG: 34,
    carbsG: 42,
    fatG: 12,
    ingredients: ["1 can (145g) tuna in spring water, drained", "1 tbsp (15g) light mayonnaise", "Mixed salad leaves", "1 wholemeal roll"],
    instructions: ["Mix the drained tuna with the mayonnaise.", "Serve on a bed of salad with the roll on the side."],
  },
  {
    meal: "lunch",
    name: "Turkey and avocado sandwich",
    description: "Turkey breast, avocado, wholemeal bread",
    quantityG: 280,
    calories: 460,
    proteinG: 30,
    carbsG: 40,
    fatG: 19,
    ingredients: ["100g sliced turkey breast", "1/2 avocado, sliced", "2 slices wholemeal bread"],
    instructions: ["Toast the bread if you like.", "Layer the turkey and avocado between the slices.", "Cut in half and serve."],
  },
  {
    meal: "lunch",
    name: "Falafel and hummus wrap",
    description: "Falafel, hummus, salad, tortilla wrap (vegetarian)",
    quantityG: 320,
    calories: 500,
    proteinG: 18,
    carbsG: 58,
    fatG: 20,
    ingredients: ["6 falafel balls (approx. 120g)", "2 tbsp (40g) hummus", "1 large tortilla wrap", "Handful of mixed salad"],
    instructions: [
      "Warm the falafel through in an oven or pan.",
      "Spread the hummus over the wrap, then add the falafel and salad.",
      "Fold and roll tightly.",
    ],
  },
  {
    meal: "lunch",
    name: "Prawn and noodle salad",
    description: "Prawns, rice noodles, mixed vegetables, soy dressing",
    quantityG: 380,
    calories: 420,
    proteinG: 32,
    carbsG: 48,
    fatG: 8,
    ingredients: ["150g cooked king prawns", "100g rice noodles (cooked weight)", "Mixed vegetables (pepper, carrot, spring onion)", "1 tbsp soy sauce"],
    instructions: [
      "Cook the noodles according to the pack instructions and drain.",
      "Toss with the prawns, vegetables and soy sauce.",
      "Serve warm or cold.",
    ],
  },

  // Dinner
  {
    meal: "dinner",
    name: "Grilled salmon with sweet potato & broccoli",
    description: "Salmon fillet, roasted sweet potato, steamed broccoli",
    quantityG: 450,
    calories: 520,
    proteinG: 38,
    carbsG: 40,
    fatG: 22,
    ingredients: ["180g salmon fillet", "1 medium sweet potato (200g), cut into wedges", "100g broccoli"],
    instructions: [
      "Preheat the oven to 200°C and roast the sweet potato wedges for 25-30 minutes.",
      "Grill or bake the salmon for 12-15 minutes until cooked through.",
      "Steam the broccoli for the last 5 minutes and serve together.",
    ],
  },
  {
    meal: "dinner",
    name: "Chicken stir-fry with noodles",
    description: "Chicken breast, egg noodles, mixed vegetables, soy sauce",
    quantityG: 450,
    calories: 540,
    proteinG: 42,
    carbsG: 55,
    fatG: 14,
    ingredients: ["180g chicken breast, sliced", "100g egg noodles (cooked weight)", "Mixed stir-fry vegetables", "2 tbsp soy sauce"],
    instructions: [
      "Stir-fry the chicken in a hot wok or pan until cooked through.",
      "Add the vegetables and cook for 3-4 minutes.",
      "Add the cooked noodles and soy sauce, tossing to combine.",
    ],
  },
  {
    meal: "dinner",
    name: "Beef mince chilli with rice",
    description: "Lean beef mince, kidney beans, basmati rice",
    quantityG: 450,
    calories: 580,
    proteinG: 40,
    carbsG: 58,
    fatG: 18,
    ingredients: ["200g lean beef mince (5% fat)", "1/2 can (200g) kidney beans", "150g basmati rice (cooked weight)", "Chopped tomatoes, onion, chilli to taste"],
    instructions: [
      "Brown the mince in a pan with the onion and chilli.",
      "Add the chopped tomatoes and kidney beans, then simmer for 15-20 minutes.",
      "Serve over the cooked rice.",
    ],
  },
  {
    meal: "dinner",
    name: "Baked cod with new potatoes & greens",
    description: "Cod fillet, new potatoes, green beans",
    quantityG: 450,
    calories: 420,
    proteinG: 36,
    carbsG: 42,
    fatG: 8,
    ingredients: ["180g cod fillet", "200g new potatoes", "100g green beans"],
    instructions: [
      "Boil the new potatoes for 15-18 minutes until tender.",
      "Bake the cod at 200°C for 15 minutes until it flakes easily.",
      "Steam the green beans and serve together.",
    ],
  },
  {
    meal: "dinner",
    name: "Lentil and vegetable curry with rice",
    description: "Red lentils, mixed vegetables, basmati rice (vegetarian)",
    quantityG: 450,
    calories: 480,
    proteinG: 18,
    carbsG: 72,
    fatG: 10,
    ingredients: ["150g red lentils", "Mixed vegetables (onion, carrot, spinach)", "1 can chopped tomatoes", "Curry spices to taste", "150g basmati rice (cooked weight)"],
    instructions: [
      "Simmer the lentils with the chopped tomatoes, spices and vegetables for 20-25 minutes until soft.",
      "Cook the rice according to the pack instructions.",
      "Serve the curry over the rice.",
    ],
  },
  {
    meal: "dinner",
    name: "Turkey meatballs with wholewheat pasta",
    description: "Turkey meatballs, tomato sauce, wholewheat pasta",
    quantityG: 450,
    calories: 550,
    proteinG: 40,
    carbsG: 60,
    fatG: 14,
    ingredients: ["200g turkey mince", "100g wholewheat pasta (dry weight)", "Passata + herbs, to make a tomato sauce"],
    instructions: [
      "Shape the turkey mince into meatballs and bake or pan-fry until cooked through.",
      "Cook the pasta according to the pack instructions.",
      "Simmer the meatballs in the tomato sauce for 5-10 minutes and serve over the pasta.",
    ],
  },

  // Snacks
  {
    meal: "snacks",
    name: "Protein shake with banana",
    description: "Whey protein, milk, banana",
    quantityG: 350,
    calories: 240,
    proteinG: 30,
    carbsG: 24,
    fatG: 3,
    ingredients: ["1 scoop (30g) whey protein powder", "250ml milk", "1 medium banana"],
    instructions: ["Add all ingredients to a blender.", "Blend until smooth and serve."],
  },
  {
    meal: "snacks",
    name: "Greek yoghurt with honey",
    description: "Greek yoghurt, honey",
    quantityG: 200,
    calories: 180,
    proteinG: 16,
    carbsG: 20,
    fatG: 3,
    ingredients: ["180g Greek yoghurt", "1 tbsp (20g) honey"],
    instructions: ["Spoon the yoghurt into a bowl.", "Drizzle over the honey and serve."],
  },
  {
    meal: "snacks",
    name: "Cottage cheese & oatcakes",
    description: "Cottage cheese, oatcakes",
    quantityG: 150,
    calories: 200,
    proteinG: 16,
    carbsG: 18,
    fatG: 7,
    ingredients: ["100g cottage cheese", "3 oatcakes"],
    instructions: ["Serve the cottage cheese with the oatcakes on the side."],
  },
  {
    meal: "snacks",
    name: "Rice cakes with peanut butter",
    description: "2 rice cakes, peanut butter",
    quantityG: 60,
    calories: 220,
    proteinG: 7,
    carbsG: 22,
    fatG: 12,
    ingredients: ["2 rice cakes", "1 tbsp (20g) peanut butter"],
    instructions: ["Spread the peanut butter over the rice cakes and serve."],
  },
  {
    meal: "snacks",
    name: "Boiled eggs",
    description: "2 boiled eggs",
    quantityG: 100,
    calories: 140,
    proteinG: 12,
    carbsG: 1,
    fatG: 10,
    ingredients: ["2 medium eggs"],
    instructions: ["Boil the eggs for 7-8 minutes for a firm yolk (5-6 minutes for soft).", "Cool briefly under cold water, then peel and serve."],
  },
  {
    meal: "snacks",
    name: "Apple with almond butter",
    description: "1 apple, almond butter",
    quantityG: 180,
    calories: 210,
    proteinG: 5,
    carbsG: 24,
    fatG: 11,
    ingredients: ["1 medium apple, sliced", "1 tbsp (20g) almond butter"],
    instructions: ["Slice the apple.", "Serve with the almond butter for dipping."],
  },

  // Extra breakfast, lunch, dinner and snack options (2026-09-03, Carl:
  // "I want as much variety as possible") — same hand-written, reviewed
  // convention as the rest of this file, not LLM-improvised at runtime.
  // Covers more proteins (pork, beef, prawns, halloumi), cuisines
  // (curry, fajitas, shakshuka) and a few more vegetarian options.
  {
    meal: "breakfast",
    name: "Lighter full English",
    description: "Eggs, bacon medallions, baked beans, toast",
    quantityG: 400,
    calories: 460,
    proteinG: 34,
    carbsG: 39,
    fatG: 18,
    ingredients: ["2 medium eggs", "2 bacon medallions", "200g baked beans", "1 slice wholemeal toast"],
    instructions: [
      "Grill or dry-fry the bacon medallions until cooked through.",
      "Fry or poach the eggs and warm the beans through in a pan.",
      "Serve together with the toast.",
    ],
  },
  {
    meal: "breakfast",
    name: "Bircher muesli",
    description: "Oats soaked overnight in apple juice, grated apple, yoghurt",
    quantityG: 300,
    calories: 360,
    proteinG: 16,
    carbsG: 55,
    fatG: 9,
    ingredients: ["50g rolled oats", "100ml apple juice", "100g Greek yoghurt", "1 apple, grated"],
    instructions: [
      "Combine the oats and apple juice in a bowl or jar, cover and refrigerate overnight.",
      "Stir through the yoghurt and grated apple before serving.",
    ],
  },
  {
    meal: "breakfast",
    name: "Breakfast burrito",
    description: "Scrambled eggs, black beans, cheese, tortilla",
    quantityG: 320,
    calories: 430,
    proteinG: 24,
    carbsG: 40,
    fatG: 18,
    ingredients: ["2 medium eggs, scrambled", "100g black beans", "30g grated cheese", "1 large tortilla wrap"],
    instructions: [
      "Scramble the eggs in a non-stick pan.",
      "Warm the beans through and grate the cheese.",
      "Layer the eggs, beans and cheese onto the tortilla, fold and roll.",
    ],
  },
  {
    meal: "breakfast",
    name: "Peanut butter banana toast with eggs",
    description: "Wholemeal toast, peanut butter, banana, boiled eggs",
    quantityG: 300,
    calories: 460,
    proteinG: 22,
    carbsG: 48,
    fatG: 20,
    ingredients: ["2 slices wholemeal bread", "1 tbsp (20g) peanut butter", "1 medium banana, sliced", "2 boiled eggs"],
    instructions: ["Toast the bread and spread with peanut butter.", "Top with banana slices.", "Serve with the boiled eggs on the side."],
  },
  {
    meal: "breakfast",
    name: "Shakshuka",
    description: "Eggs poached in spiced tomato sauce, crusty bread",
    quantityG: 380,
    calories: 400,
    proteinG: 22,
    carbsG: 35,
    fatG: 20,
    ingredients: ["2 medium eggs", "1 can chopped tomatoes", "1/2 onion, diced", "1 tsp paprika/cumin", "1 slice crusty bread"],
    instructions: [
      "Soften the onion in a pan, add the tomatoes and spices, and simmer for 10 minutes.",
      "Make two wells in the sauce and crack in the eggs; cover and cook until just set.",
      "Serve with the bread for dipping.",
    ],
  },
  {
    meal: "breakfast",
    name: "Porridge with nuts and seeds",
    description: "Porridge oats, milk, mixed nuts, mixed seeds",
    quantityG: 350,
    calories: 420,
    proteinG: 16,
    carbsG: 45,
    fatG: 18,
    ingredients: ["50g porridge oats", "250ml milk", "15g mixed nuts, chopped", "10g mixed seeds"],
    instructions: ["Cook the oats and milk in a pan for 3-4 minutes, stirring, until thick.", "Top with the nuts and seeds and serve."],
  },

  {
    meal: "lunch",
    name: "Beef and vegetable stir-fry with rice",
    description: "Lean beef strips, mixed vegetables, basmati rice",
    quantityG: 450,
    calories: 540,
    proteinG: 38,
    carbsG: 55,
    fatG: 16,
    ingredients: ["180g lean beef strips", "Mixed stir-fry vegetables", "150g basmati rice (cooked weight)", "2 tbsp soy sauce"],
    instructions: [
      "Stir-fry the beef in a hot wok for 2-3 minutes until browned.",
      "Add the vegetables and soy sauce, cooking for a further 3-4 minutes.",
      "Serve over the cooked rice.",
    ],
  },
  {
    meal: "lunch",
    name: "Halloumi and roasted veg salad",
    description: "Grilled halloumi, roasted vegetables, mixed leaves (vegetarian)",
    quantityG: 350,
    calories: 420,
    proteinG: 20,
    carbsG: 30,
    fatG: 24,
    ingredients: ["100g halloumi, sliced", "Mixed vegetables (courgette, pepper, red onion)", "Mixed salad leaves", "1 tbsp olive oil"],
    instructions: [
      "Roast the vegetables in the oil at 200°C for 20 minutes.",
      "Grill the halloumi slices for 1-2 minutes per side until golden.",
      "Toss everything together with the salad leaves.",
    ],
  },
  {
    meal: "lunch",
    name: "Ham and cheese toastie with salad",
    description: "Ham, cheese, wholemeal bread, side salad",
    quantityG: 300,
    calories: 460,
    proteinG: 26,
    carbsG: 38,
    fatG: 22,
    ingredients: ["2 slices wholemeal bread", "80g sliced ham", "30g grated cheese", "Side salad"],
    instructions: ["Layer the ham and cheese between the bread.", "Toast in a sandwich press or pan until golden and the cheese melts.", "Serve with the side salad."],
  },
  {
    meal: "lunch",
    name: "Quinoa, chickpea and feta salad",
    description: "Quinoa, chickpeas, feta, mixed vegetables (vegetarian)",
    quantityG: 380,
    calories: 460,
    proteinG: 18,
    carbsG: 55,
    fatG: 18,
    ingredients: ["80g quinoa (dry weight)", "1/2 can (120g) chickpeas", "50g feta, crumbled", "Diced cucumber and tomato"],
    instructions: [
      "Cook the quinoa according to the pack instructions and leave to cool slightly.",
      "Mix in the chickpeas, cucumber and tomato.",
      "Top with the crumbled feta and serve.",
    ],
  },
  {
    meal: "lunch",
    name: "BBQ chicken pitta with slaw",
    description: "Grilled chicken, BBQ sauce, pitta bread, coleslaw",
    quantityG: 350,
    calories: 490,
    proteinG: 36,
    carbsG: 50,
    fatG: 14,
    ingredients: ["150g grilled chicken breast, sliced", "1 tbsp BBQ sauce", "1 wholemeal pitta", "60g coleslaw"],
    instructions: ["Toss the sliced chicken through the BBQ sauce.", "Warm the pitta and split it open.", "Fill with the chicken and coleslaw."],
  },
  {
    meal: "lunch",
    name: "Salmon and new potato salad",
    description: "Salmon fillet, new potatoes, mixed salad leaves",
    quantityG: 400,
    calories: 480,
    proteinG: 32,
    carbsG: 38,
    fatG: 22,
    ingredients: ["150g salmon fillet", "200g new potatoes", "Mixed salad leaves", "1 tsp olive oil, lemon juice"],
    instructions: [
      "Boil the new potatoes for 15-18 minutes until tender, then halve.",
      "Grill or pan-fry the salmon for 4-5 minutes per side.",
      "Toss the potatoes and salad leaves with the oil and lemon juice, and serve with the salmon.",
    ],
  },

  {
    meal: "dinner",
    name: "Roast chicken with roasted vegetables",
    description: "Chicken breast, roasted root vegetables",
    quantityG: 450,
    calories: 500,
    proteinG: 42,
    carbsG: 35,
    fatG: 20,
    ingredients: ["200g chicken breast", "Mixed root vegetables (carrot, parsnip, potato)", "1 tbsp olive oil", "Herbs to taste"],
    instructions: [
      "Toss the vegetables in the oil and roast at 200°C for 30-35 minutes.",
      "Season and roast or pan-fry the chicken until cooked through.",
      "Serve together.",
    ],
  },
  {
    meal: "dinner",
    name: "Pork chops with mash and green beans",
    description: "Pork chop, mashed potato, green beans",
    quantityG: 450,
    calories: 540,
    proteinG: 40,
    carbsG: 40,
    fatG: 22,
    ingredients: ["1 pork chop (200g)", "250g potatoes", "100g green beans", "Splash of milk for mash"],
    instructions: [
      "Boil the potatoes for 15-20 minutes, then mash with a splash of milk.",
      "Grill or pan-fry the pork chop for 6-8 minutes per side until cooked through.",
      "Steam the green beans and serve together.",
    ],
  },
  {
    meal: "dinner",
    name: "Prawn and vegetable curry with rice",
    description: "King prawns, mixed vegetables, curry sauce, basmati rice",
    quantityG: 450,
    calories: 480,
    proteinG: 34,
    carbsG: 55,
    fatG: 12,
    ingredients: ["180g king prawns", "Mixed vegetables (pepper, spinach, onion)", "Curry sauce (tomato/coconut base)", "150g basmati rice (cooked weight)"],
    instructions: [
      "Soften the onion and vegetables in a pan, then add the curry sauce and simmer for 10 minutes.",
      "Add the prawns and cook for a further 3-4 minutes until pink through.",
      "Serve over the cooked rice.",
    ],
  },
  {
    meal: "dinner",
    name: "Vegetable and halloumi skewers with couscous",
    description: "Halloumi, mixed vegetables, couscous (vegetarian)",
    quantityG: 400,
    calories: 460,
    proteinG: 20,
    carbsG: 50,
    fatG: 20,
    ingredients: ["120g halloumi, cubed", "Mixed vegetables (courgette, pepper, red onion)", "80g couscous (dry weight)", "1 tsp olive oil"],
    instructions: [
      "Thread the halloumi and vegetables onto skewers and grill for 8-10 minutes, turning occasionally.",
      "Prepare the couscous according to the pack instructions.",
      "Serve the skewers over the couscous.",
    ],
  },
  {
    meal: "dinner",
    name: "Beef steak with sweet potato fries and salad",
    description: "Lean steak, sweet potato fries, side salad",
    quantityG: 450,
    calories: 560,
    proteinG: 42,
    carbsG: 42,
    fatG: 24,
    ingredients: ["200g lean steak", "1 medium sweet potato (200g), cut into fries", "Side salad", "1 tsp olive oil"],
    instructions: [
      "Toss the sweet potato fries in the oil and bake at 200°C for 25-30 minutes.",
      "Season and pan-fry or grill the steak to your liking.",
      "Serve with the fries and side salad.",
    ],
  },
  {
    meal: "dinner",
    name: "Chicken fajitas",
    description: "Chicken breast, peppers, onion, tortillas",
    quantityG: 420,
    calories: 520,
    proteinG: 40,
    carbsG: 48,
    fatG: 16,
    ingredients: ["180g chicken breast, sliced", "1 pepper and 1 onion, sliced", "Fajita seasoning", "2 small tortillas"],
    instructions: [
      "Toss the chicken in the fajita seasoning.",
      "Stir-fry the chicken, pepper and onion in a hot pan for 6-8 minutes until cooked through.",
      "Warm the tortillas and serve the filling alongside for wrapping.",
    ],
  },

  {
    meal: "snacks",
    name: "Hummus with carrot and cucumber sticks",
    description: "Hummus, carrot and cucumber sticks",
    quantityG: 200,
    calories: 180,
    proteinG: 6,
    carbsG: 18,
    fatG: 9,
    ingredients: ["60g hummus", "1 carrot, cut into sticks", "1/2 cucumber, cut into sticks"],
    instructions: ["Serve the hummus with the carrot and cucumber sticks for dipping."],
  },
  {
    meal: "snacks",
    name: "Mixed nuts",
    description: "A small handful of mixed nuts",
    quantityG: 30,
    calories: 180,
    proteinG: 6,
    carbsG: 6,
    fatG: 16,
    ingredients: ["30g mixed unsalted nuts"],
    instructions: ["Portion out and eat."],
  },
  {
    meal: "snacks",
    name: "Protein bar",
    description: "1 standard protein bar",
    quantityG: 60,
    calories: 220,
    proteinG: 20,
    carbsG: 22,
    fatG: 8,
    ingredients: ["1 protein bar (approx. 60g)"],
    instructions: ["Check the specific bar's own label for exact macros — this is a typical estimate."],
  },
  {
    meal: "snacks",
    name: "Banana with peanut butter",
    description: "1 banana, peanut butter",
    quantityG: 150,
    calories: 240,
    proteinG: 7,
    carbsG: 30,
    fatG: 11,
    ingredients: ["1 medium banana", "1 tbsp (20g) peanut butter"],
    instructions: ["Slice the banana and serve with the peanut butter for dipping, or spread directly."],
  },
  {
    meal: "snacks",
    name: "Turkey slices with cheese",
    description: "Sliced turkey breast, cheese",
    quantityG: 100,
    calories: 180,
    proteinG: 20,
    carbsG: 2,
    fatG: 10,
    ingredients: ["60g sliced turkey breast", "30g cheese"],
    instructions: ["Serve the turkey and cheese together."],
  },
  {
    meal: "snacks",
    name: "Edamame beans",
    description: "Steamed, lightly salted edamame beans",
    quantityG: 150,
    calories: 170,
    proteinG: 16,
    carbsG: 12,
    fatG: 7,
    ingredients: ["150g edamame beans (in pods or shelled)", "Pinch of salt"],
    instructions: ["Steam or boil the edamame for 4-5 minutes.", "Drain and toss with a pinch of salt."],
  },
];
